### ISSUE TITLE
Update to PyPy v5.7

### ISSUE THREAD

**Issue by dstufft** [docker-library/pypy#13]
PyPy 5.7 is released, supporting Python 2.7 and Python 3.5. It would be great to get this added.

**Comment by tianon** [comment]
Thanks for the prod, @dstufft :heart: :heart:!

**Comment by dstufft** [comment]
Cool, I'm not familiar with the release processes here. What's the typical lead time on this being available to docker pull?

**Comment by tianon** [comment]
Normally we'd wait for https://doi-janky.infosiftr.net/job/update.sh/job/pypy/ to run that `update.sh` change, but I'm going to just run it manually now (since we know it needs it), then we'll make a PR to https://github.com/docker-library/official-images (similar to https://github.com/docker-library/official-images/pull/2762, which has the `pypy2` half of this version bump), and once that's merged it'll be built officially and pushed.

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/pull/2766 for `pypy3-5.7.0` :+1:
