### ISSUE TITLE
Release 7.3.1

### ISSUE THREAD

**Issue by johnthagen** [docker-library/pypy#41]
[PyPy 7.3.1 was released April 10, 2020](https://morepypy.blogspot.com/2020/04/pypy-731-released.html). It would be great for the Docker image to be updated for this.

**Comment by tianon** [comment]
Our automated updates (https://doi-janky.infosiftr.net/job/update.sh/job/pypy/) have been failing thanks to https://foss.heptapod.net/pypy/pypy/issues/3210, which was fixed in https://foss.heptapod.net/pypy/pypy/commit/fbbe06715eb48df1a03640672d99335695d3e47c, but unfortunately still isn't in a release yet.
