### ISSUE TITLE
No images for `arm64` available

### ISSUE THREAD

**Issue by casabre** [docker-library/pypy#72]
After trying to run e.g. `podman run -it pypy:3.9` at a Raspberry Pi running Ubuntu 20.04, the following errors are popping up.

```shell
podman run pypy:3.9
✔ docker.io/library/pypy:3.9
Trying to pull docker.io/library/pypy:3.9...
Error: choosing an image from manifest list docker://pypy:3.9: no image found in manifest list for architecture arm64, variant "v8", OS linux
```

At least, the tags at Dockerhub are indicating that there should be an `arm64` build.

**Comment by wglambert** [comment]
https://github.com/docker-library/pypy/issues/17#issuecomment-1055762812
>Unfortunately, we're having to remove this support again in #69 thanks to linking changes (`libffi.so.6` and `libtinfow.so.6`). :disappointed:

**Comment by casabre** [comment]
@wglambert does this apply only to `bullseye` images? `buster` would work?
Is there any fix on the long run planned? Maybe upstream?

**Comment by wglambert** [comment]
Progress is being made on the issue https://github.com/docker-library/pypy/pull/69#issuecomment-1061057221

In the meantime these image hashes are from a few weeks ago, before the change https://github.com/docker-library/repo-info/tree/f5351e649ad726be7b992a1b058edf8eb52bcf4d/repos/pypy/remote

The latest 3.9-Bullseye version with arm64 support https://github.com/docker-library/repo-info/blob/f5351e649ad726be7b992a1b058edf8eb52bcf4d/repos/pypy/remote/bullseye.md#pypybullseye---linux-arm64-variant-v8
And 3.9-Buster https://github.com/docker-library/repo-info/blob/f5351e649ad726be7b992a1b058edf8eb52bcf4d/repos/pypy/remote/buster.md#pypybuster---linux-arm64-variant-v8

So you can still pull the old images from Dockerhub, if the specific tags for the variant have changed then the hash would otherwise work
```console
docker pull pypy@sha256:e00cbbeee185c4f1a2ff90fa9bf8bd6e4bf04ad2dd6fe0407d421df430435517
```

**Comment by tianon** [comment]
#73 is going to bring these back again :+1:
